accountapp/urls.py
from django.urls import path
from . import views

app_name="accountapp"
urlpatterns = [
    path('login/',views.login_view, name="login"),
    path('register/', views.register, name="register"),
    path('logout/',views.logout_view, name="logout"),
]

caveapp/urls.py
from django.urls import path
from . import views

app_name="caveapp"
urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('menu/', views.menu, name="menu"),

    path('events/', views.events, name="events"),
    path('chefs/', views.chefs, name="chefs"),
    path('gallery/', views.gallery, name="gallery"),
    path('contacts/', views.contacts, name="contacts"),
    path('booking/', views.booking, name="booking"),
    path('contact/', views.contact_view, name='contact'),
    path('show_booking/', views.retrieve_booking, name="show_booking"),
    path('delete/<int:id>', views.delete_booking, name="delete_booking"), #delete

    path('edit/<int:booking_id>',views.update_booking, name="update_booking"),
    path('my_bookings/', views.my_bookings, name='my_bookings'), 
    path('create_booking/', views.booking, name='create_booking'),
    path('retrieve_booking/', views.retrieve_booking, name='retrieve_booking'),


    path('pay/', views.pay, name='pay'),
    path('stk/', views.stk, name='stk'),
    path('token/', views.token, name='token'),
]

proj_building/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('caveapp.urls')),
    path('accountapp/', include('accountapp.urls')),
    path('uploadapp/', include('uploadapp.urls')),
    
]

uploadapp/urls.py
from django.urls import path
from . import views

app_name="uploadapp"
urlpatterns = [
    path('upload/', views.upload_image, name='upload_image'),
    path('images/', views.view_images, name='view_images'),
    path('upload/success/', views.upload_success, name='upload_success'),
]

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}About Us{% endblock  %}
{% block content %}
<!-- About Section -->
 <section id="about" class="about section">

    <div class="container" data-aos="fade-up" data-aos-delay="100">

      <div class="row gy-4">
        <div class="col-lg-6 order-1 order-lg-2">
          <img src="{% static 'assets/img/table-5356682_1280.jpg' %}" alt="">
        </div>
        <div class="col-lg-6 order-2 order-lg-1 content">
          {% comment %} <h3>Distinct Luxury Camp</h3> {% endcomment %}
          <p class="fst-italic">
           About Us
         </p>
          <ul>
            <li><i class="bi bi-check2-all"></i> <span>Welcome to Northern Safaris' Camp, a unique retreat nestled in the heart of Samburu, Northern Kenya, along the tranquil Ewaso Nyiro River. Located between three iconic national reserves—Shaba, Samburu, and Buffalo—our lodge offers breathtaking views of the Sabashe Mountain, a perfect hiking spot for our guests.

              At Northern Safaris' Camp, we celebrate the rich culture of the local Samburu community, inviting guests to experience their traditional dances, unique dressing codes, and cultural practices through interactive experiences.
              
              Our camp features 12 cottages and 20 tents, all ensuite and offering stunning river views. With a total of 150 beds, the design and location of our accommodation provide guests with a serene and breezy stay. Additionally, our beautiful swimming pool offers the perfect place to relax and unwind amidst nature..</span></li>


          </ul> 
     
        </div>
      </div>

    </div>

  </section><!-- /About Section -->
  {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Home | Tiger's Cave Camp Restaurant</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  


  
{% comment %}   
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon"> {% endcomment %}

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  
  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  <title>{% block title %}{% endblock  %}</title>


</head>

<body class="index-page">
    {% include "header.html" %}

  
  

  <main class="main">
     {% block content %}
     {% if messages %}
<ul>
  {% for message in messages %} 
  <li style="color: {% if message.tags == 'error' %}red{% else %}green{% endif %};">
    {{ message }}
  </li>
  {% endfor %}
</ul>
{% endif %} 
    

  


   

   
   
    {% endblock %}
  </main>
   {% include "footer.html" %} 



  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/booking.html
{% extends "base.html" %}
{% load static %}
{% block title %}About Us{% endblock  %}

{% block content %}
<!-- Book A Table Section -->
<section id="book-a-table" class="book-a-table section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>RESERVATION</h2>
      <p>Book a Table</p>
    </div><!-- End Section Title -->

    <div class="container" data-aos="fade-up" data-aos-delay="100">

      <form method="POST">
        {% csrf_token %}
        <div class="row gy-4">
          <div class="col-lg-4 col-md-6">
            <label for="name" class="form-label">Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required="">
          </div>
          <div class="col-lg-4 col-md-6">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required="">
          </div>
          <div class="col-lg-4 col-md-6">
            <label for="phone" class="form-label">Phone</label>
            <input type="tel" class="form-control" name="phone" id="phone" placeholder="Your Phone" required="">
          </div>
            <div class="col-lg-4 col-md-6">
              <label for="date_check_in" class="form-label">Date Check-In</label>
              <input type="datetime-local" name="date_check_in" class="form-control datepicker" id="date_check_in" placeholder="Check-In Date" required="">
          </div>
          <div class="col-lg-4 col-md-6">
            <label for="date_check_out" class="form-label">Date Check-Out</label>
            <input type="datetime-local" name="date_check_out" class="form-control datepicker" id="date_check_out" placeholder="Check-Out Date" required="">
        </div>
          <div class="col-lg-4 col-md-6">
            <label for="number" class="form-label">Number of Guest</label>
            <input type="number" class="form-control" name="number" id="number" placeholder="number" required="">
          </div>
        </div>

        <div class="form-group mt-3">
          <label for="message" class="form-label">Message</label>
          <textarea class="form-control" name="message" rows="5" placeholder="Message"></textarea>
        </div>

        <div class="text-center mt-3">
          <div class="loading">Loading</div>
          <div class="error-message"></div>
          <div class="sent-message">Your booking request was sent. We will call back or send an Email to confirm your reservation. Thank you!</div>
          <button type="submit">Book a Table</button>
        </div>
      </form><!-- End Reservation Form -->

    </div>

  </section><!-- /Book A Table Section -->

{% endblock %}

templates/chefs.html
{% extends "base.html" %}
{% load static %}

{% block title %}Our chefs {% endblock  %}

{% block content %}
<!-- Chefs Section -->
<section id="chefs" class="chefs section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>Team</h2>
      <p>Meet Our qualified chefs</p>
    </div><!-- End Section Title -->

    <div class="container">

      <div class="row gy-4">

        <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
          <div class="member">
            <img src="{% static 'assets/img/chefs\ai-generated-8600463_1280.jpg' %}" class="img-fluid" alt="">
            <div class="member-info">
              <div class="member-info-content">
                <h4>John Kariuki</h4>
                <span>Master Chef</span>
              </div>
              <div class="social">
                <a href=""><i class="bi bi-twitter-x"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div><!-- End Team Member -->

        <div class="col-lg-4" data-aos="fade-up" data-aos-delay="200">
          <div class="member">
            <img src="{% static 'assets/img\chefs\sarah photo.jpg' %}" class="img-fluid" alt="">
            <div class="member-info">
              <div class="member-info-content">
                <h4>Sarah Lekimaroro</h4>
                <span>Patissier</span>
              </div>
              <div class="social">
                <a href=""><i class="bi bi-twitter-x"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div><!-- End Team Member -->

        <div class="col-lg-4" data-aos="fade-up" data-aos-delay="300">
          <div class="member">
            <img src="{% static 'assets/img\chefs\cooking-8911937_1280.jpg' %}" class="img-fluid" alt="">
            <div class="member-info">
              <div class="member-info-content">
                <h4>Nasieku Lelengu</h4>
                <span>Cook</span>
              </div>
              <div class="social">
                <a href=""><i class="bi bi-twitter-x"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div><!-- End Team Member -->

      </div>

    </div>

  </section><!-- /Chefs Section -->
{% endblock %}

templates/dumb.html
def Contacts(request):
    """Contact Us"""
    if request.method == 'POST':
       #Create variable to pick the input fields
        contacts = Contacts(
            name = request.POST['name'],
            email = request.POST['email'],
           subject= request.POST['subject'],
            message = request.POST['message'],       
        )

        contacts.save()
        #redirect to a page
        return redirect('caveapp:home')
    else:
        return render(request, 'contacts.html',)
















from django.db import models

# Create your models here.
class Booking(models.Model):
    """Booking table"""
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=10)
    date_check_in = models.DateTimeField()
    date_check_out = models.DateTimeField()  
    number = models.CharField(max_length=100)
    message = models.TextField()

    
    def __str__(self):
        return self.name



        
@login_required
def booking(request):
    """create booking"""
    if request.method == 'POST':
       #Create variable to pick the input fields
        booking = Booking(
            name = request.POST['name'],
            email = request.POST['email'],
            phone = request.POST['phone'],
            date_check_in = request.POST['date_check_in'],
            date_check_out = request.POST['date_check_out'],
            number = request.POST['number'],
            message = request.POST['message'],       
        )

        booking.save()
        #redirect to a page
        return redirect('caveapp:home')
    else:
        return render(request, 'booking.html',)


        # retrieve all appointments
        def retrieve_booking(request):
            """retrieve/fetch all booking"""
        # create variable to store these booking
            booking=Booking.objects.all()
            context= {'booking':booking}
            return render(request,'show_booking.html', context)
    














































def create_booking(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        date_check_in = request.POST['date_check_in']
        date_check_out = request.POST['date_check_out']
        number = request.POST['number']
        message = request.POST['message']

        booking = Booking(
            name=name,
            email=email,
            phone=phone,
            date_check_in=date_check_in,
            date_check_out=date_check_out,
            number=number,
            message=message
        )
        booking.save()
        #redirect to a page
        return redirect('caveapp:index')
    else:
        return render(request, 'booking.html',)
    

 # retrieve all appointments
def retrieve_booking(request):
    """retrieve/fetch all booking"""
# create variable to store these booking
    booking=Booking.objects.all()
    context= {'booking':booking}
    return render(request,'show_booking.html', context)




    {% extends "base.html" %}
{% block title %}Show Booking{% endblock  %}

{% block content %}
<table class="table table-light-responsive">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>phone</th>
            <th>date_check_in</th>
            <th>date_check_out</th>
            <th>number</th>
            <th>message</th>
            
        </tr>

    </thead>
    <tbody>
        {% for booking in booking %}
       <tr>
        <td>{{booking.name}}</td>
        <td>{{booking.email}}</td>
        <td>{{booking.phone}}</td>
        <td>{{booking.check_date_in}}</td>
        <td>{{booking.check_date_out}}</td>
        <td>{{booking.number}}</td>
        <td>{{booking.message}}</td>
       
        <td>
          
        </td>
       </tr>
       {% endfor %} 
    </tbody>
</table>
{% endblock %}

@admin.register(Booking)
class BookingAdmin(admin.ModelAdmin):
    list_display = ('name', 'email', 'phone', 'date_check_in', 'date_check_out', 'number','message')
    list_filter = ('date_check_in', 'date_check_out')
    search_fields = ('name', 'email', 'phone')



    from django.db import models

# Create your models here.
class UploadImage(models.Model):
    title = models.CharField(max_length=100) #Image title
    image = models.ImageField(upload_to='uploaded_mage') #folder to save images
    def __str__(self):
        return self.title

templates/events.html
{% extends "base.html" %}
{% load static %}
{% block title %} Our Events {% endblock  %}

{% block content %}

    <!-- Events Section -->
    <section id="events" class="events section">

        <img class="slider-bg" src="{% static 'assets/img/events-bg.jpg' %}" alt="" data-aos="fade-in">
  
        <div class="container">
  
          <div class="swiper init-swiper" data-aos="fade-up" data-aos-delay="100">
            <script type="application/json" class="swiper-config">
              {
                "loop": true,
                "speed": 600,
                "autoplay": {
                  "delay": 5000
                },
                "slidesPerView": "auto",
                "pagination": {
                  "el": ".swiper-pagination",
                  "type": "bullets",
                  "clickable": true
                }
              }
            </script>
            <div class="swiper-wrapper">
  
              <div class="swiper-slide">
                <div class="row gy-4 event-item">
                  <div class="col-lg-6">
                    <img src="{% static 'assets/img/events-slider/events-slider-1.jpg' %}" class="img-fluid" alt="">
                  </div>
                  <div class="col-lg-6 pt-4 pt-lg-0 content">
                    <h3>Birthday Parties</h3>
                    <div class="price">
                      <p><span>$189</span></p>
                    </div>
                    <p class="fst-italic">
                      Birthday Party at Northern Safaris' Camp
                    </p>
                    <ul>
                      <li><i class="bi bi-check2-circle"></i> <span>Celebrate your special day in a truly unforgettable setting at Northern Safaris'
                   Camp! Nestled between the stunning landscapes of Samburu and overlooking the majestic Sabashe Mountain, our camp offers the perfect backdrop for a memorable birthday celebration. Whether you're looking for a serene gathering with family and friends or an adventurous outdoor party, we tailor the experience to suit your needs.

                        Enjoy delicious meals from our menu, immerse yourself in the local Samburu culture with traditional dances, and take in breathtaking views of the surrounding national reserves. Our team will ensure that every detail of your birthday is taken care of, from decorations to activities, creating a unique and personalized event that will leave you with lasting memories. Let Tiger's Cave Camp make your birthday an extraordinary experience!.</span></li>
                      
                    </ul>
                  
                  </div>
                </div>
              </div><!-- End Slider item -->
  
              <div class="swiper-slide">
                <div class="row gy-4 event-item">
                  <div class="col-lg-6">
                    <img src="{% static 'assets\img\wine-6174460_1280.jpg' %}" class="img-fluid" alt="">
                  </div>
                  <div class="col-lg-6 pt-4 pt-lg-0 content">
                    <h3>Private Parties at Northen Safaris' Camp</h3>
                    <div class="price">
                      <p><span>$290</span></p>
                    </div>
                    <p class="fst-italic">
                      Celebrate your special moments in a truly extraordinary setting at Northen Safaris' Camp. Whether it's a birthday, anniversary, or a private gathering with friends and family, our camp offers the perfect venue for an intimate and memorable event. Located in the picturesque Samburu region, with stunning views of the Ewaso Nyiro River and the majestic Sabashe Mountain, our camp provides a unique and serene environment for any occasion.

Our dedicated team will work with you to create a personalized experience, from customizing the menu to organizing entertainment and decorations. You can also immerse yourself in the local Samburu culture, with traditional dances and the chance to interact with the community. Whether you prefer an indoor celebration or an outdoor event under the stars, Tiger's Cave Camp guarantees a private party that will leave you and your guests with unforgettable memories.
                    </p>
                   
                  </div>
                </div>
              </div><!-- End Slider item -->
  
              <div class="swiper-slide">
                <div class="row gy-4 event-item">
                  <div class="col-lg-6">
                    <img src="{% static 'assets\img\concert-3387324_1280.jpg' %}" class="img-fluid" alt="">
                  </div>
                  <div class="col-lg-6 pt-4 pt-lg-0 content">
                    <h3>Custom Parties</h3>
                    <div class="price">
                      <p><span>$99</span></p>
                    </div>
                    <p class="fst-italic">
                      Welcome to Custom Parties at Northen Safaris' Camp
                    </p>
                    <ul>
                      <li><i class="bi bi-check2-circle"></i> <span>At Northen Safaris' Camp, we understand that every celebration is unique, which is why we offer customized parties tailored to your specific needs and preferences. Whether you're planning a themed event, a corporate gathering, or a special milestone celebration, we work closely with you to bring your vision to life in a stunning natural setting.

                        Our camp’s breathtaking location between three national reserves and with direct views of Sabashe Mountain offers the perfect backdrop for any custom event. You can choose from a range of flexible venues, from intimate outdoor spaces by the river to stylish indoor settings. Our expert team will handle everything, from personalized menus and decor to music and entertainment, ensuring your event is seamless and unforgettable.
                        
                        We also offer the opportunity to incorporate the rich cultural heritage of the local Samburu community into your event, with traditional dances, music, and authentic experiences. Whatever your celebration, Northen Safaris' Camp provides a one-of-a-kind environment where your custom party becomes an unforgettable occasion..</span></li>
                      
                    </ul>
                    
                  </div>
                </div>
              </div><!-- End Slider item -->
  
            </div>
            <div class="swiper-pagination"></div>
          </div>
  
        </div>
  
      </section><!-- /Events Section -->
{% endblock %}

templates/footer.html
{% load static %}
<footer id="footer" class="footer">

    <div class="container footer-top">
      <div class="row gy-4">
        <div class="col-lg-4 col-md-6 footer-about">
          <a href="index.html" class="logo d-flex align-items-center">
            <span class="sitename">Restaurant</span>
          </a>
          <div class="footer-contact pt-3">
            <p>A 02 </p>
            <p>Samburu, Archer's Post 535022</p>
            <p class="mt-3"><strong>Phone:</strong> <span>+254 69866204</span></p>
            <p><strong>Email:</strong> <span>lenajonathan02@gmail.com</span></p>
          </div>
          <div class="social-links d-flex mt-4">
            <a href=""><i class="bi bi-twitter-x"></i></a>
            <a href=""><i class="bi bi-facebook"></i></a>
            <a href=""><i class="bi bi-instagram"></i></a>
            <a href=""><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Terms of service</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-md-3 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Product Management</a></li>
            <li><a href="#">Marketing</a></li>
            <li><a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-4 col-md-12 footer-newsletter">
          <h4>Our Newsletter</h4>
          <p>Subscribe to our newsletter and receive the latest news about our products and services!</p>
          <form action="forms/newsletter.php" method="post" class="php-email-form">
            <div class="newsletter-form"><input type="email" name="email"><input type="submit" value="Subscribe"></div>
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your subscription request has been sent. Thank you!</div>
          </form>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">Restaurant</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">Jonathan Lenairewa</a>
      </div>
    </div>

  </footer>

templates/header.html
{% load static %}
 <style>
  header {
    background-color: light blue;
  }
</style>

<header id="header" class="header fixed-top">

    <div class="topbar d-flex align-items-center">
      <div class="container d-flex justify-content-center justify-content-md-between">
        <div class="contact-info d-flex align-items-center">
          <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">lenajonathan02@gmail.com</a></i>
          <i class="bi bi-phone d-flex align-items-center ms-4"><span>+254 769866204</span></i>
        </div>
        <div class="languages d-none d-md-flex align-items-center">
          <ul>
            <li>En</li>
            <li><a href="#">De</a></li>
            <li><a href="{% url 'accountapp:register' %}"class="">Register</a><li>
            <li><a href="{% url 'accountapp:login' %}"class="">Login</a><li>
              <li><a href="{% url 'accountapp:logout' %}"class="">Logout</a><li>
            <li><a href="{% url 'uploadapp:upload_image' %}"class="">uploadImage</a><li>
          </ul>
        </div>
      </div>
    </div><!-- End Top Bar -->

    <div class="branding d-flex align-items-cente">

      <div class="container position-relative d-flex align-items-center justify-content-between">
        <a href="index.html" class="logo d-flex align-items-center me-auto me-xl-0">
          <!-- Uncomment the line below if you also wish to use an image logo -->
          <!-- <img src="assets/img/logo.png" alt=""> -->
          <h1 class="sitename">Northern Safaris' Camp</h1>
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li><a href="{% url 'caveapp:home' %}" class="active">Home<br></a></li>
            <li><a href="{% url 'caveapp:about' %}">About</a></li>
            <li><a href="{% url 'caveapp:menu' %}">Menu</a></li> 
            <li><a href="{% url 'caveapp:events' %}">Events</a></li>
            <li><a href="{% url 'caveapp:chefs' %}">Chefs</a></li>
            <li><a href="{% url 'caveapp:gallery' %}">Gallery</a></li>
            <li><a href="{% url 'caveapp:contacts' %}">Contact</a></li>
            
        
           
          </ul> 
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

        <a class="btn-book-a-table d-none d-xl-block" href="{% url "caveapp:booking" %}">Book a Table</a> 

        <a href="{% url 'caveapp:my_bookings' %}">My Bookings</a>
 
       
          

      </div>

    </div>

  </header>

templates/pay.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2>Make a Payment</h2>

<form method="post" action="{% url 'caveapp:stk' %}">
  {% csrf_token %}
    <label class="form-label" for="phone">Phone Number :</label>
    <input type="number" id="phone" name="phone" value="254" placeholder="Phone Number">
    <br><br>

    <label class="form-label" for="amount">Amount :</label>
    <input type="text" id="amount" name="amount" placeholder="Amount">

    <br><br>
  <button type="submit" class="btn btn-success">Submit</button>
</form>


{% endblock %}

templates/show_booking.html
{% extends "base.html" %}
{% block title %}Show Booking{% endblock  %}

{% block content %}
<table class="table table-dark-responsive">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>phone</th>
            <th>date_check_in</th>
            <th>date_check_out</th>
            <th>number</th>
            <th>message</th>
            
        </tr>

    </thead>
    <tbody>
        {% for booking in booking %}
       <tr>
        <td>{{booking.name}}</td>
        <td>{{booking.email}}</td>
        <td>{{booking.phone}}</td>
        <td>{{booking.date_check_in}}</td>
        <td>{{booking.date_check_out}}</td>
        <td>{{booking.number}}</td>
        <td>{{booking.message}}</td>
       
        <td>
            <a href="{% url 'caveapp:update_booking' booking.id %}">Edit</a>
            <a href="{% url 'caveapp:delete_booking' booking.id %}"class="btn btn-danger">Delete</a>
            <a href="{% url 'caveapp:pay' %}" class="btn btn-success">Pay</a>
        </td>
       </tr>
       {% endfor %} 
    </tbody>
</table>
{% endblock %}